/**
 * This file was auto-generated by scripts/generate-types.js
 * Do not modify this file directly.
 */

export interface BaseModel {
    id: string;
    created: string;
    updated: string;
    [key: string]: any;
}

export interface AuthModel extends BaseModel {
    email: string;
    emailVisibility: boolean;
    verified: boolean;
}

export interface _superusers extends AuthModel {
    tokenKey: string; 
} 

export interface Members extends AuthModel {
    tokenKey: string; 
    contact_ptr?: string; 
} 

export interface Users extends AuthModel {
    tokenKey: string; 
    name?: string; 
    avatar?: string; 
    role?: "Attorney" | "Staff"; 
} 

export interface _authOrigins extends BaseModel {
    collectionRef: string; 
    recordRef: string; 
    fingerprint: string; 
} 

export interface _externalAuths extends BaseModel {
    collectionRef: string; 
    recordRef: string; 
    provider: string; 
    providerId: string; 
} 

export interface _mfas extends BaseModel {
    collectionRef: string; 
    recordRef: string; 
    method: string; 
} 

export interface _otps extends BaseModel {
    collectionRef: string; 
    recordRef: string; 
    password: any; 
    sentTo?: string; 
} 

export interface Allegations extends BaseModel {
    strategy: string; 
    related_element?: string; 
    content: string; 
    is_contested?: boolean; 
} 

export interface Areas extends BaseModel {
    name?: string; 
    matter?: string; 
} 

export interface CaseTypes extends BaseModel {
    case_type?: string; 
} 

export interface Contacts extends BaseModel {
    first_name?: string; 
    last_name?: string; 
    phone?: string; 
    email?: string; 
    type?: "Individual" | "Company"; 
    designation?: "Client" | "Opposing Party" | "Counsel" | "Expert" | "Witness" | "Other"; 
    is_portal_enabled?: boolean; 
    address?: string; 
    address2?: string; 
    city?: string; 
    state?: string; 
    zip?: string; 
} 

export interface Documents extends BaseModel {
    file?: string; 
    matter?: string; 
    uploaded_by?: string; 
    visible_to_portal?: boolean; 
    title?: string; 
    summary?: string; 
    exhibit_number?: string; 
    bates_start?: string; 
    bates_end?: string; 
    tags?: any; 
    ai_processed?: boolean; 
    page_count?: number; 
    order_index?: number; 
    original_filename?: string; 
    areas?: string[]; 
    description?: string; 
    state?: string; 
} 

export interface EvidenceLinks extends BaseModel {
    allegation: string; 
    document: string; 
    witness?: string; 
    probative_grade?: number; 
    reasoning?: string; 
} 

export interface LegalStrategies extends BaseModel {
    matter: string; 
    type: "claim" | "defense"; 
    title: string; 
    elements?: any; 
    moving_party?: string; 
    target_party?: string; 
} 

export interface MatterParticipants extends BaseModel {
    matter?: string; 
    contact?: string; 
    role?: string; 
    is_billing_contact?: boolean; 
    portal_access?: boolean; 
} 

export interface Matters extends BaseModel {
    title?: string; 
    case_number?: string; 
    description?: string; 
    status?: "Open" | "Closed" | "Archived"; 
    lead_attorney?: string; 
    case_type?: string; 
} 

export interface Snippets extends BaseModel {
    title?: string; 
    content?: any; 
    tags?: any; 
} 

export interface Tasks extends BaseModel {
    title?: string; 
    description?: string; 
    due_date?: string; 
    completed?: boolean; 
    estimated_hours?: number; 
    date_completed?: string; 
    archived?: boolean; 
    completed_by?: string; 
    webhook_trigger?: string; 
    tags?: any; 
    users?: string[]; 
    priority?: "Low" | "Medium" | "High"; 
} 

export interface Templates extends BaseModel {
    title?: string; 
    content?: any; 
    category?: string; 
    tags?: any; 
} 

export interface TimeEntries extends BaseModel {
    matter?: string; 
    user?: string; 
    description?: string; 
    duration?: number; 
} 

